export type ISOLanguageCode =
  | "en" // English
  | "es" // Spanish
  | "fr" // French
  | "de" // German
  | "zh" // Chinese
  | "ja" // Japanese
  | "ar" // Arabic
  | "pt" // Portuguese
  | "ru" // Russian
  | "ko" // Korean
  | "it" // Italian
  | "nl" // Dutch
  | "sv" // Swedish
  | "da" // Danish
  | "fi" // Finnish
  | "no" // Norwegian
  | "pl" // Polish
  | "tr" // Turkish
  | "cs" // Czech
  | "hu" // Hungarian
  | "el" // Greek
  | "he" // Hebrew
  | "th" // Thai
  | "id" // Indonesian
  | "ms" // Malay
  | "vi" // Vietnamese
  | "uk" // Ukrainian
  | "ro" // Romanian
  | "bg" // Bulgarian
  | "hr" // Croatian
  | "sk" // Slovak
  | "sl" // Slovenian
  | "et" // Estonian
  | "lv" // Latvian
  | "lt" // Lithuanian
  | "is" // Icelandic
  | "ga" // Irish
  | "eu" // Basque
  | "ca" // Catalan
  | "gl" // Galician
  | "mk" // Macedonian
  | "sr" // Serbian
  | "az" // Azerbaijani
  | "ka" // Georgian
  | "hy" // Armenian
  | "sq" // Albanian
  | "bs" // Bosnian
  | "fa" // Persian
  | "ur" // Urdu
  | "hi" // Hindi
  | "bn" // Bengali
  | "gu" // Gujarati
  | "kn" // Kannada
  | "ml" // Malayalam
  | "mr" // Marathi
  | "pa" // Punjabi
  | "ta" // Tamil
  | "te" // Telugu
  | "si" // Sinhala
  | "my" // Burmese
  | "km" // Khmer
  | "lo" // Lao
  | "mn" // Mongolian
  | "ne" // Nepali
  | "si" // Sinhala
  | "sw" // Swahili
  | "am" // Amharic
  | "zu" // Zulu
  | "xh" // Xhosa
  | "af" // Afrikaans
  | "sn" // Shona
  | "yo" // Yoruba
  | "ha" // Hausa
  | "ig" // Igbo
  | "ff" // Fulah
  | "om" // Oromo
  | "ti" // Tigrinya
  | "so" // Somali
  | "ks" // Kashmiri
  | "sd" // Sindhi
  | "cy" // Welsh
  | "gd" // Scottish Gaelic
  | "gv" // Manx
  | "kw" // Cornish
  | "fy" // Frisian
  | "li" // Limburgan
  | "wa" // Walloon
  | "sg" // Sango
  | "lu" // Luba-Katanga
  | "kg" // Kongo
  | "rn" // Rundi
  | "rw" // Kinyarwanda
  | "mg" // Malagasy
  | "ny" // Chichewa
  | "ch" // Chamorro
  | "sm" // Samoan
  | "to" // Tongan
  | "fj" // Fijian
  | "mh" // Marshallese
  | "na" // Nauru
  | "gil" // Gilbertese (Note: ISO 639-2/3 code, not 639-1)
  | "mi" // Maori
  | "gn" // Guarani
  | "ay" // Aymara
  | "qu" // Quechua
  | "oj" // Ojibwa
  | "nv" // Navajo
  | "cr" // Cree
  | "iu" // Inuktitut
  | "ik" // Inupiaq
  | "cho" // Choctaw (Note: ISO 639-2/3 code, not 639-1)
  | "chr" // Cherokee (Note: ISO 639-2/3 code, not 639-1)
  | "co" // Corsican
  | "fo" // Faroese
  | "kl" // Kalaallisut
  | "lb" // Luxembourgish
  | "mg" // Malagasy
  | "mt" // Maltese
  | "oc" // Occitan
  | "rm" // Romansh
  | "sc" // Sardinian
  | "sr" // Serbian
  | "tl" // Tagalog
  | "ts" // Tsonga
  | "tn" // Tswana
  | "ve" // Venda
  | "xh" // Xhosa
  | "zu"; // Zulu
